### ISSUE TITLE
Not storing failures to .respec_failures

### ISSUE THREAD

**Issue by TheStranjer** [oggy/respec#13]
Hi there,

I'm using Ubuntu 14.04 LTS, and when I run respec, it doesn't seem to save the failures to .respec_failures, which is the entire point of this gem. It works fine on a Mac.

**Comment by oggy** [comment]
I'm guessing you were running into an RSpec 2 vs rspec 3 issue. Try the latest version, which I've just fixed to work under RSpec 3.

**Comment by carolmirakove** [comment]
I am experiencing this same issue using the latest, `0.8.1` - no failures are writing to `.respec_failures`. When I run my rspec tests I have one failed example and the file is not created. If I run `respec f`a message in the terminal says 'no failed tests', then the file `.respec_failures` is created, then all of the examples from my repo are run and recorded in `.respec_failures`.
Questions toward troubleshooting:
- Is `respec` not compatible with certain versions of `rspec`? I tried  `3.0.0` and `3.2.0`
- Is any certain formatting required? I tried specifying none and `--format documentation`. 
I'm working on Mac OS 10.10.2. 
Thanks for this gem and advice.

**Comment by oggy** [comment]
@carolmirakove 

It's working for me with rspec 3.2.0 on Yosemite. Respec 0.8.1.

Demo shell session below. You shouldn't need to specify any formatter options. It *should* work fine with any that you specify (I run it with Fuubar regularly), but to narrow down on the problem, try without any.

If that doesn't help, you might need to dig in with a debugger to see why it doesn't create the failures file. Respec prints the rspec command that it invokes. You'll see it loads [this file](https://github.com/oggy/respec/blob/master/lib/respec/formatter.rb) -- I'm curious what failures_path evaluates to.

```
g@woosh:~/tmp [m] $ cat test_spec.rb 
describe 'test' do
  it 'fails' do
    expect(1).to eq(2)
  end
end
g@woosh:~/tmp [m] $ respec test_spec.rb 
++ rspec test_spec.rb /Users/g/.rvm/gems/ruby-2.1.5/gems/respec-0.8.1/lib/respec/formatter.rb
F

Failures:

  1) test fails
     Failure/Error: expect(1).to eq(2)
       
       expected: 2
            got: 1
       
       (compared using ==)
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-expectations-3.2.0/lib/rspec/expectations/fail_with.rb:29:in `fail_with'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-expectations-3.2.0/lib/rspec/expectations/handler.rb:38:in `handle_failure'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-expectations-3.2.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-expectations-3.2.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-expectations-3.2.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-expectations-3.2.0/lib/rspec/expectations/expectation_target.rb:54:in `to'
     # ./test_spec.rb:3:in `block (2 levels) in <top (required)>'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:177:in `instance_exec'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:177:in `block in run'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:385:in `block in with_around_and_singleton_context_hooks'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:343:in `block in with_around_example_hooks'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:474:in `block in run'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:612:in `run_around_example_hooks_for'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:474:in `run'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:343:in `with_around_example_hooks'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:385:in `with_around_and_singleton_context_hooks'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:174:in `run'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:548:in `block in run_examples'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:544:in `map'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:544:in `run_examples'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:512:in `run'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:110:in `block (3 levels) in run_specs'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:110:in `map'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:110:in `block (2 levels) in run_specs'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1526:in `with_suite_hooks'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:109:in `block in run_specs'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/reporter.rb:62:in `report'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:108:in `run_specs'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:86:in `run'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:70:in `run'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:38:in `invoke'
     # /Users/g/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.0/exe/rspec:4:in `<top (required)>'
     # /Users/g/.rvm/gems/ruby-2.1.5/bin/rspec:23:in `load'
     # /Users/g/.rvm/gems/ruby-2.1.5/bin/rspec:23:in `<main>'
     # /Users/g/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
     # /Users/g/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

Finished in 0.00309 seconds (files took 0.23328 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./test_spec.rb:2 # test fails

g@woosh:~/tmp [m] $ cat .respec_failures 
test fails
```

**Comment by carolmirakove** [comment]
@oggy I made a foolish usage mistake - I ran my original set of tests with `rspec` instead of `respec`. Your demo helped me realize my error. Works perfectly - thank you, this is a very useful gem!

**Comment by oggy** [comment]
@carolmirakove Awesome -- glad it's useful!
